name: Deploy Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-unknown-unknown
      - name: Build WASM
        run: cargo rustc --lib --target wasm32-unknown-unknown --release --crate-type cdylib
      - name: Sync WASM to docs
        run: cp target/wasm32-unknown-unknown/release/mzc.wasm docs/mzc.wasm
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: 'docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
